[kuafu]
listenAt="0.0.0.0:5577"
consulAddr="localhost:8500"
trustProxies=["127.0.0.1"]
trustedPlatform="X-Real-IP"
accessLog="/tmp/kuafu.access.log"
logFile="/tmp/kuafu.all.log"
fallback="127.0.0.1:3000"
prefix="/_inner/hello2429527/"
superUser="admin"
superPass="admin"
secret="893287rvnlflidsfdsyuf2nvxfuoiiwgo7weoyfgodiwefegfdffdsfdsiofwefdogfsfwofwe7r823fdfdsiiwgo7weoyfgodiwefefdsfdsioffdsfsddogfswofwe7r823fdfdsfdsfdsfiiwgo7weoyfgodiwefefdsfdsiofofwe7r823fdfdsiiwgo7weoyfgodiwefefdsfdsiofwofwe7r823fdfdsgoyfgodiwefefdsfdsiofwwe7r823fdfdsgsfe542twgoyfgodiwefefdsfdsioofwe7r823fdfdsgoyfdsfsdfdsfoguycxlfheyo726rewfdsgdsyiufdsfdsfdsf"

[host."dist.shifen.de"]
	root="/Users/xurenlu/Sites/write.git/frontend/dist/"

[host."boot.shifen.de"]
	extractors = [
		{type="jwt",method="insert",config={secret="hellobabyWhatareyoudoing",from="header",target="Authorization"}},
		{type="copy",method="insert",config={from="header",to="_wjId"}},
		{type="copy",method="insert",config={from="header",to="_ip"}},
		{type="ip",method="update",config={"target"="_ip"}}]
	validators=[
		{type="basic",weight=[-1,10000],config={"username"="admin","password"="admin"}},
		{type="whitelist",weight=[-1,10000],config={"list"=["abcd","efghi"],target="_wjId"}},
		{type="blacklist",weight=[-100000,100],config={"list"=["abcd","efghi"],target="_wjId"}},
		{type="blacklist",weight=[-1,100],config={list=["abcd","efghi"],target="_ip"}},
		{type="private-ip",weight=[-1,100]},
		{type="not-empty",weight=[-1,100],config={target="_wjId"}}
	]
	root="/Users/xurenlu/Sites/bootshiro/src/main/resources/static"
	loginUrl= "https://glogin.shifen.de/github/login?_returnUrl=https://boot.shifen.de/"


[host."test.404.ms"]
	backends=["localhost:3388"]
	upstreamHeaders={client-testing="2022.2.25"}
	autoCors = true
		headers = {content-type="text/html",accept="application/json",x-Support="renlu/1.2.1"}
		method="basic"
		authName="lanyi"
		authPass="lanyi2027"



