[kuafu]
listenAt="0.0.0.0:5588"
consulAddr="localhost:8500"
trustProxies=["127.0.0.1"]
trustedPlatform="X-Real-IP"
accessLog="/tmp/kuafu.access.log"
logFile="/tmp/kuafu.all.log"
fallback="127.0.0.1:3000"
prefix="/_inner/hello2429527/"
superUser="admin"
superPass="admin"
secret="8932952787rvnlflidsfdsyuf2nvxfuoiiwgo7weoyfgodiwefegfdffdsfdsiofwefdogfsfwofwe7r823fdfdsiiwgo7weoyfgodiwefefdsfdsioffdsfsddogfswofwe7r823fdfdsfdsfdsfiiwgo7weoyfgodiwefefdsfdsiofofwe7r823fdfdsiiwgo7weoyfgodiwefefdsfdsiofwofwe7r823fdfdsgoyfgodiwefefdsfdsiofwwe7r823fdfdsgsfe542twgoyfgodiwefefdsfdsioofwe7r823fdfdsgoyfdsfsdfdsfoguycxlfheyo726rewfdsgdsyiufdsfdsfdsf"
handlers=[
	{ type="dingding",config={key="dingjaleikitg0yo7opk", jwtSecret="8932952787rvnlflidsfdsyuf2nvxfuoiiwgo7weoyfgodiwefegfdffdsfdsiofwefdogfsfwofw",secret="_S53dZiphIkqfH-qZdLm8gGM004ov7ZvDpzOxAZe0pPgzvwwrcdJNYTvDlQ00L9s",corpId="2535257623"},entry="/_plugin/dingding" },
	{ type="github",config={},entry="/_plugin/github/" },
	{ type="wework",config={},entry="/_plugin/wework/" }
]

[host."dist.shifen.de"]
	root="/Users/xurenlu/Sites/write.git/frontend/dist/"

[host."local.shifen.de"]
	extractors = [
		{type="jwt",method="insert",config={secret="8932952787rvnlflidsfdsyuf2nvxfuoiiwgo7weoyfgodiwefegfdffdsfdsiofwefdogfsfwofw",source="cookie",from="_wjToken"}},
		{type="copy",method="update",config={from="_wjId",to="id"}},
		{type="copy",method="update",config={from="_wjName",to="name"}},
		{type="header",method="update",config={from="X-Real-IP",to="_ip"}},
		{type="cookie",method="update",config={from="_wjId",to="id"}},
		{type="ip",method="update",config={to="remote_ip"}}]
	validators=[
		{type="all-true",weight=-1},
		{type="basic",weight=10000,config={"username"="admin","password"="admin"}},
		{type="in-list",weight=10000,config={"list"=["abcd","efghi"],target="_wjId"}},
		{type="in-list",weight=-100000,config={"list"=["badgues-1","budguys-2"],target="_wjId"}},
		{type="in-list",weight=100,config={list=["abcd","efghi"],target="_ip"}},
		{type="private-ip",weight=100},
		{type="non-empty",weight=100,config={target="Email"}}
	]
	loginUrl= "http://boot.shifen.de:5588/_plugin/dingding/login?_returnUrl=%CURRENT_URL%"


[host."boot.shifen.de"]
	root="/Users/xurenlu/Sites/bootshiro/src/main/resources/static"



