name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.18

    - name: tidy
      run: go mod tidy

    - name: Install dependencies
      run: go mod download

    - name: Build
      run: go build -v -o ./kuafu ./src/

    - name: Test
      run: go test -v ./src/

    - name: Server
      run: ./kuafu test --config ./etc/main.toml --pid /tmp/kuafu.pid

